# Generated by Django 3.2.7 on 2021-09-12 14:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('business_name', models.CharField(max_length=30, verbose_name='Business Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('city', models.CharField(max_length=30, verbose_name='City Name')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('email_address', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Your Client ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('email_address', models.EmailField(help_text='Enter a valid email address', max_length=50)),
                ('phone_number', models.CharField(help_text='Enter a valid ten digit phone number', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('already_sent', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Sent'), ('U', 'Unsent')], default='U', help_text='Email to be sent today.', max_length=1)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='online_database.customer')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
