# Generated by Django 3.2.7 on 2021-10-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_address',
            new_name='email',
        ),
    ]
