# Generated by Django 3.2.7 on 2021-09-12 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailstatus',
            options={'ordering': ['already_sent']},
        ),
        migrations.AlterField(
            model_name='emailstatus',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID For Customer To Be Contacted.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emailstatus',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('U', 'Unsent')], default='U', help_text='Has the email already been sent?', max_length=1),
        ),
    ]
