# Generated by Django 3.2.7 on 2021-09-12 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0002_auto_20210913_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstatus',
            name='sent_email_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='Your Client ID'),
        ),
        migrations.AlterField(
            model_name='emailstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
