# Generated by Django 3.2.7 on 2021-09-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0004_auto_20210913_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='online_database.emailstatus'),
        ),
    ]
