# Generated by Django 3.2.7 on 2021-09-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0007_sendemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
