# Generated by Django 3.2.7 on 2021-09-19 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0008_delete_sendemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=50, verbose_name='Email Subject')),
                ('message', models.CharField(max_length=1000, verbose_name='Email Message')),
            ],
        ),
    ]
