# Generated by Django 3.2.7 on 2021-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0010_auto_20210922_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=15),
        ),
    ]
