# Generated by Django 3.2.7 on 2021-09-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0011_customer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
