# Generated by Django 3.2.7 on 2021-10-22 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_database', '0012_remove_customer_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, verbose_name='Business Name')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('message', models.CharField(max_length=150, verbose_name='Request Message')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=50, verbose_name='Email Address')),
            ],
        ),
    ]
